
VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.provider = 'virtualbox'
    
  config.vm.define "net1" do | n1 |
    n1.vm.box= 'ubuntu/jammy64'
    n1.vm.host_name = "net1"

    n1.vm.network "private_network", ip: "192.168.56.5"
    
      n1.vm.provider :virtualbox do |res|

        res.customize ["modifyvm", :id, "--cpus", "2"]
        res.customize ["modifyvm", :id, "--memory", "2000"]
      end

  end

  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "net" => ["net1"]
    }
    ansible.playbook = "playbook.yml"
    ansible.compatibility_mode = "2.0"
  end

end